# Étape 1 : Utiliser une image de base Node.js
FROM node:18 AS build

# Étape 2 : Définir le répertoire de travail
WORKDIR /app

# Étape 3 : Copier les fichiers de package
COPY package*.json ./

# Étape 4 : Installer les dépendances
RUN npm install

# Étape 5 : Copier le reste des fichiers de l'application
COPY . .

# Étape 6 : Construire l'application React
RUN npm run build

# Étape 7 : Utiliser une image nginx pour servir l'application
FROM nginx:alpine

# Étape 8 : Copier les fichiers construits vers Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Étape 9 : Exposer le port Nginx (modifie si nécessaire)
EXPOSE 80

# Étape 10 : Lancer Nginx
CMD ["nginx", "-g", "daemon off;"]
