version: '3.8'

services:
    server:
        build:
            context: ./server
        ports:
            - '5000:5000'
        environment:
            - MONGODB_URI=${MONGODB_URI} # Assure-toi que cette variable d'environnement est bien définie
        # Retire depends_on si tu n'as plus besoin de Mongo localement

    client:
        build:
            context: ./client
        ports:
            - '3000:3000'
