version: '3.8'

services:
    server:
        build:
            context: ./server
        ports:
            - '5000:5000'
        environment:
            - MONGODB_URI
        depends_on:
            - mongo

    mongo:
        image: mongo
        ports:
            - '27017:27017'

    client:
        build:
            context: ./client
        ports:
            - '3000:3000'
