version: '3.8'
services:
    server:
        build:
            context: .
            dockerfile: server/Dockerfile
        ports:
            - '5000:5000'
        environment:
            - MONGODB_URI=${{ secrets.MONGODB_URI }} # Variable d'environnement pour MongoDB Atlas
