# Utiliser l'image Node.js officielle
FROM node:14

# Créer le répertoire de l'application
WORKDIR /usr/src/app

# Copier package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste de l'application
COPY . .

# Exposer le port
EXPOSE 5000

# Commande pour démarrer l'application
CMD ["npm", "start"]
