# Étape 1 : Utiliser une image de base Node.js
FROM node:18

# Étape 2 : Définir le répertoire de travail
WORKDIR /app

# Étape 3 : Copier les fichiers de package
COPY package*.json ./

# Étape 4 : Installer les dépendances
RUN npm install

# Étape 5 : Copier le reste des fichiers de l'application
COPY . .

# Étape 6 : Exposer le port de l'application (modifie si nécessaire)
EXPOSE 5000

# Étape 7 : Lancer l'application
CMD ["npm", "start"]
