name: CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: Build backend
              run: |
                  cd server
                  npm install
                  npm run build

            - name: Build frontend
              run: |
                  cd client
                  npm install
                  npm run build

            - name: Build Docker images
              run: |
                  docker-compose -f docker-compose.yml build

            - name: Push to Render
              env:
                  RENDER_API_KEY: ${{ secrets.VAPOSHOP_PROD }}
              run: |
                  curl -X POST "https://api.render.com/v1/deploy/srv-csdrgn5svqrc73943qag" \
                  -H "Content-Type: application/json" \
                  -H "Authorization: Bearer $RENDER_API_KEY" \
                  -d '{"branch": "main"}'
